import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory: __dirname });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      ".next-test/**",
      "out/**",
      "verifier/**",
      "tests/**",
      // Generated by Next.js on every build — not hand-maintained.
      "next-env.d.ts",
    ],
  },
];

export default config;
